### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Shame-fight** [jelly54/pytorch_train#2]
请给个数据集地址~

**Comment by tf2jaguar** [comment]
请不要用于商业，发生的一切利益往来均与本人无关
https://drive.google.com/drive/folders/18EunmjOJsbE5Lh9zA0cZ4wKV6Um46dkg?usp=sharing

**Comment by 12138wjj** [comment]
??

**Comment by tf2jaguar** [comment]
> ??

楼上有数据集链接哈
